@startuml physical_l4

left to right direction

package Blended4Future {

    interface tcp_int as "Port: 80 (TCP)"
    node vtm as "Ubuntu Virtual Machine" {

        interface nginx_backend as "'/api'"
        interface nginx_frontend as "'/'"

        node nginx as "Nginx Proxy Server" {

            node frontend_docker as "Frontend Docker Image" {
                component frontend as "Frontend"
                interface frontend_interface as "Port: 3000"
                frontend -d- frontend_interface
            }
            interface frontend_docker_int as "Port: 3000"
            
            interface backend_docker_int as "Port: 4000"
            node backend_docker as "Backend Docker Image" {
                database db as "Database (Volume)"
                component backend as "Backend"
                interface backend_interface as "Port: 8080"
                db -l- backend
                backend -d- backend_interface
            }

            backend_interface -d[dotted]- backend_docker_int
            frontend_interface -d[dotted]- frontend_docker_int

            frontend_docker_int -[dotted]- nginx_frontend
            backend_docker_int -[dotted]- nginx_backend
        }
        
        nginx_backend -- tcp_int
        nginx_frontend -- tcp_int
        
    }
    vtm -[hidden]- tcp_int

}

@enduml